// Perl 脚本 生成系统调用号和用户态的系统调用封装函数
print "# Autogenerated file. Do not edit!\n\n";
print "#include \"kernel/syscall.h\"\n\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}


entry("hello"); # 示例系统调用